version: "3.3"
services:

  model:
    container_name: "model-service"
    build:
      context: ./Model
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"

  game-manager:
    container_name: "game-manager-service"
    build:
      context: ./GameManager
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    #tty: true

  persistence:
    container_name: "persistence-service"
    build:
      context: ./Persistence
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true

  root:
    container_name: "root-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    depends_on:
      - game-manager
      - persistence
      - model
    environment:
      DISPLAY:  141.70.105.162:0.0

  postgres:
    # docker-compose exec postgres /bin/bash
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: schachmeister420
      POSTGRES_PASSWORD: schachconnoisseur
      POSTGRES_DB: schachdb
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db:
    driver: local