version: "3.3"
services:

  postgres:
    # docker-compose exec postgres /bin/bash
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: schachmeister420
      POSTGRES_PASSWORD: schachconnoisseur
      POSTGRES_DB: schachdb
    restart: unless-stopped

